package shim

import (
	"os"
	"path/filepath"
	"slices"
	"testing"
)

func must(t *testing.T, err error) {
	t.Helper()
	if err != nil {
		t.Fatal(err)
	}
}

// assertShim checks that path is the entry point of alias.
func assertShim(t *testing.T, path, alias string) {
	t.Helper()
	fi, err := os.Lstat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !fi.Mode().IsRegular() || fi.Mode().Perm()&0o111 == 0 {
		t.Fatalf("%s should be an executable regular file, mode %v", path, fi.Mode())
	}
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "#!/bin/sh\n" +
		"# Generated by `dockshim install`, do not edit: change the config and run it again.\n" +
		"exec dockshim run --shim \"$0\" '" + alias + "' \"$@\"\n"
	if string(content) != want {
		t.Fatalf("shim %s:\n%s\nwant:\n%s", path, content, want)
	}
}

func TestInstall(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "bin")
	res, err := Install(dir, []string{"node", "php"})
	if err != nil || !slices.Equal(res.Created, []string{"node", "php"}) {
		t.Fatalf("res=%+v err=%v", res, err)
	}
	assertShim(t, filepath.Join(dir, "php"), "php")

	res, err = Install(dir, []string{"node", "php"})
	if err != nil || len(res.Created)+len(res.Removed) != 0 {
		t.Fatalf("second install changed things: %+v", res)
	}

	// A shim that lost its executable bit is repaired.
	must(t, os.Chmod(filepath.Join(dir, "node"), 0o644))
	res, err = Install(dir, []string{"node", "php"})
	if err != nil || !slices.Equal(res.Created, []string{"node"}) {
		t.Fatalf("res=%+v err=%v", res, err)
	}
	assertShim(t, filepath.Join(dir, "node"), "node")

	// Anything that isn't an entry point is removed, and changed entry points are rewritten.
	must(t, os.WriteFile(filepath.Join(dir, "foreign"), nil, 0o755))
	must(t, os.Symlink("/old/place/dockshim", filepath.Join(dir, "link")))
	must(t, os.Mkdir(filepath.Join(dir, "empty"), 0o755))
	must(t, os.WriteFile(filepath.Join(dir, "php"), []byte("#!/bin/sh\n"), 0o755))
	must(t, os.Symlink("/old/place/dockshim", filepath.Join(dir, "composer")))
	res, err = Install(dir, []string{"composer", "php"})
	if err != nil {
		t.Fatal(err)
	}
	if !slices.Equal(res.Created, []string{"composer", "php"}) || !slices.Equal(res.Removed, []string{"empty", "foreign", "link", "node"}) {
		t.Fatalf("res=%+v", res)
	}
	assertShim(t, filepath.Join(dir, "php"), "php")
	assertShim(t, filepath.Join(dir, "composer"), "composer")
	entries, err := os.ReadDir(dir)
	must(t, err)
	if len(entries) != 2 {
		t.Fatalf("entries = %v", entries)
	}
}

func TestInstallNeverRemovesRecursively(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "bin")
	keep := filepath.Join(dir, "sub", "keep")
	must(t, os.MkdirAll(filepath.Dir(keep), 0o755))
	must(t, os.WriteFile(keep, nil, 0o644))
	if _, err := Install(dir, []string{"php"}); err == nil {
		t.Fatal("expected an error for a non-empty directory")
	}
	if _, err := os.Stat(keep); err != nil {
		t.Fatal("non-empty directory was wiped")
	}
}
