// Package shim manages the alias entry points: /bin/sh scripts running `dockshim run --shim`,
// with dockshim resolved through PATH.
package shim

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/squrious/dockshim/internal/config"
)

// format is bumped whenever the script changes, so that future versions can tell old shims apart.
const format = 1

// marker identifies a script as ours.
const marker = "# " + config.ToolName + " shim format "

// versionPrefix starts the line naming the dockshim version that wrote the script. It is
// informational only: it is ignored when deciding whether a shim is up to date.
const versionPrefix = "# created by " + config.ToolName + " "

// IsShim reports whether path is one of our entry points: a regular file carrying our marker.
func IsShim(path string) bool {
	fi, err := os.Lstat(path)
	if err != nil || !fi.Mode().IsRegular() {
		return false
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()
	head := make([]byte, 512)
	n, _ := f.Read(head)
	return strings.Contains(string(head[:n]), marker)
}

// script passes its own path, so that discovery is anchored at the shim, and the alias name
// explicitly, so that a renamed copy or a case-insensitive lookup still runs the same alias.
func script(version, alias string) []byte {
	return fmt.Appendf(nil, `#!/bin/sh
# Generated by `+"`"+config.ToolName+" install`"+`, do not edit: change the config and run it again.
%s%d, alias %q
%s%s
exec %s run --shim "$0" %s "$@"
`, marker, format, alias, versionPrefix, version, config.ToolName, shellQuote(alias))
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Result reports what Install changed, by alias name.
type Result struct {
	Created []string
	Removed []string
	Skipped []string // existing files that are not shims
}

// Install makes dir contain exactly one entry point per alias. version is recorded in the scripts.
// Entry points of aliases no longer listed are removed; files that are not shims are never touched.
// On error, the Result still lists what was done before it.
func Install(dir, version string, aliases []string) (Result, error) {
	var res Result
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return res, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return res, err
	}
	for _, e := range entries {
		p := filepath.Join(dir, e.Name())
		if !slices.Contains(aliases, e.Name()) && IsShim(p) {
			if err := os.Remove(p); err != nil {
				return res, err
			}
			res.Removed = append(res.Removed, e.Name())
		}
	}

	for _, alias := range aliases {
		p := filepath.Join(dir, alias)
		want := script(version, alias)
		switch _, err := os.Lstat(p); {
		case err == nil && !IsShim(p):
			res.Skipped = append(res.Skipped, alias)
			continue
		case err == nil && upToDate(p, want):
			continue
		}
		if err := create(p, want); err != nil {
			return res, fmt.Errorf("installing %s: %w", alias, err)
		}
		res.Created = append(res.Created, alias)
	}
	return res, nil
}

func upToDate(path string, want []byte) bool {
	// Only the owner bit is required: the umask may strip the others.
	fi, err := os.Stat(path)
	if err != nil || fi.Mode().Perm()&0o100 == 0 {
		return false
	}
	content, err := os.ReadFile(path)
	return err == nil && bytes.Equal(withoutVersion(content), withoutVersion(want))
}

func withoutVersion(content []byte) []byte {
	var out []byte
	for line := range bytes.Lines(content) {
		if !bytes.HasPrefix(line, []byte(versionPrefix)) {
			out = append(out, line...)
		}
	}
	return out
}

// create writes the script through a temporary file, so an in-use shim is replaced atomically.
func create(path string, content []byte) error {
	tmp := path + ".dockshim-tmp"
	_ = os.Remove(tmp)
	if err := os.WriteFile(tmp, content, 0o755); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
