// Package shim manages the alias entry points: /bin/sh scripts running `dockshim run --shim`,
// with dockshim resolved through PATH. Their directory belongs to dockshim: it holds the entry
// points and nothing else.
package shim

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/squrious/dockshim/internal/config"
)

// script passes its own path, so that discovery is anchored at the shim, and the alias name
// explicitly, so that a renamed copy or a case-insensitive lookup still runs the same alias.
func script(alias string) []byte {
	return fmt.Appendf(nil, `#!/bin/sh
# Generated by `+"`"+config.ToolName+" install`"+`, do not edit: change the config and run it again.
exec %s run --shim "$0" %s "$@"
`, config.ToolName, shellQuote(alias))
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Result reports what Install changed, by entry name.
type Result struct {
	Created []string
	Removed []string
}

// Install makes dir contain exactly one entry point per alias: missing or changed ones are
// written, anything else is removed. Removal is never recursive: a non-empty directory is an error.
// On error, the Result still lists what was done before it.
func Install(dir string, aliases []string) (Result, error) {
	var res Result
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return res, err
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		return res, err
	}
	for _, e := range entries {
		if slices.Contains(aliases, e.Name()) {
			continue
		}
		if err := os.Remove(filepath.Join(dir, e.Name())); err != nil {
			return res, err
		}
		res.Removed = append(res.Removed, e.Name())
	}

	for _, alias := range aliases {
		p := filepath.Join(dir, alias)
		want := script(alias)
		if upToDate(p, want) {
			continue
		}
		if err := create(p, want); err != nil {
			return res, fmt.Errorf("installing %s: %w", alias, err)
		}
		res.Created = append(res.Created, alias)
	}
	return res, nil
}

func upToDate(path string, want []byte) bool {
	// Only the owner bit is required: the umask may strip the others.
	fi, err := os.Lstat(path)
	if err != nil || !fi.Mode().IsRegular() || fi.Mode().Perm()&0o100 == 0 {
		return false
	}
	content, err := os.ReadFile(path)
	return err == nil && bytes.Equal(content, want)
}

// create writes the script through a temporary file, so an in-use shim is replaced atomically.
func create(path string, content []byte) error {
	tmp := path + ".dockshim-tmp"
	_ = os.Remove(tmp)
	if err := os.WriteFile(tmp, content, 0o755); err != nil {
		return err
	}
	if err := os.Rename(tmp, path); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
